package com.penglecode.xmodule.myexample.model;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 商品信息 (t_product) 实体类
 * 
 * @author Mybatis-Generator
 * @date	2019年06月27日 下午 13:31:53
 */
@Model(name="商品信息")
public class Product implements BaseModel<Product> {
     
    private static final long serialVersionUID = 1L;

    /** 商品ID */
    @Id
    private Long productId;

    /** 商品名称 */
    private String productName;

    /** 商品分类：1-实物商品，0-虚拟商品 */
    private Integer productType;

    /** 商品单价 */
    private Double unitPrice;

    /** 商品库存 */
    private Integer inventory;

    /** 商品主要分类 */
    private Long mainCategoryId;

    /** 创建时间 */
    private String createTime;

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getProductType() {
        return productType;
    }

    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Integer getInventory() {
        return inventory;
    }

    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    public Long getMainCategoryId() {
        return mainCategoryId;
    }

    public void setMainCategoryId(Long mainCategoryId) {
        this.mainCategoryId = mainCategoryId;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            
        }

        public MapBuilder withProductId(Long ... productId) {
            modelProperties.put("productId", BaseModel.first(productId, getProductId()));
            return this;
        }

        public MapBuilder withProductName(String ... productName) {
            modelProperties.put("productName", BaseModel.first(productName, getProductName()));
            return this;
        }

        public MapBuilder withProductType(Integer ... productType) {
            modelProperties.put("productType", BaseModel.first(productType, getProductType()));
            return this;
        }

        public MapBuilder withUnitPrice(Double ... unitPrice) {
            modelProperties.put("unitPrice", BaseModel.first(unitPrice, getUnitPrice()));
            return this;
        }

        public MapBuilder withInventory(Integer ... inventory) {
            modelProperties.put("inventory", BaseModel.first(inventory, getInventory()));
            return this;
        }

        public MapBuilder withMainCategoryId(Long ... mainCategoryId) {
            modelProperties.put("mainCategoryId", BaseModel.first(mainCategoryId, getMainCategoryId()));
            return this;
        }

        public MapBuilder withCreateTime(String ... createTime) {
            modelProperties.put("createTime", BaseModel.first(createTime, getCreateTime()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}