#SpringBoot自动配置开启debug模式
debug: false

#应用日志配置
logging:
    file: ${spring.application.name}
    config: classpath:log4j2-spring.xml

#Spring上下文初始化程序
context:
    initializer:
        classes: com.penglecode.xmodule.common.initializer.DefaultSpringAppPreInitializer
        
#Servlet容器配置
server:
    port: 18080

#SpringBoot应用监控模块
management:
    endpoints:
        web:
            base-path: /admin/actuator
            exposure:
                include: 'gateway'
    endpoint:
        gateway:
            enabled: true
        shutdown:
            enabled: false
        health:
            show-details: always
    health:
        defaults:
            enabled: false
        
#SpringBoot应用的名称
spring:
    #被排除的自动配置
    autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
          - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
    
    profiles:
        active: dev

    #Spring国际化配置
    messages:
        basename: config/i18/messages
        cache-duration: -1
        encoding: UTF-8
    #关闭JMX监控
    jmx:
        enabled: false