#SpringBoot自动配置开启debug模式
debug: true

#应用日志配置
logging:
    config: classpath:log4j2-spring.xml

#Spring上下文初始化程序
context:
    initializer:
        classes: com.penglecode.xmodule.common.initializer.DefaultSpringAppPreInitializer

#Servlet容器配置
server:
    port: 8080
    servlet:
        context-path: /xmodule-examples-jersey
        application-display-name: xmodule-examples-jersey
        session.timeout: 1800

#SpringBoot应用的名称
spring:
    application:
        name: xmodule-examples-jersey
    #被排除的自动配置
    autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
          - org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration
          - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
          - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
          - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
        
    profiles:
        active: dev

    #Spring国际化配置
    messages:
        basename: config/i18/messages
        cache-duration: -1
        encoding: UTF-8
    #关闭JMX监控
    jmx:
        enabled: false
    #开启Web#CharacterEncodingFilter
    http:
        encoding:
            enabled: true
            charset: UTF-8
            force: true
    jersey:
        type: filter
        application-path: /
        filter:
            order: -2147483640
        init:
            jersey.config.servlet.filter.forwardOn404: true
            jersey.config.servlet.filter.staticContentRegex: (/static/.*)|(.+\.html)|(.+\.css)|(.+\.js)|(.+\.jpg)|(.+\.jpeg)|(.+\.png)|(.+\.gif)|(/upload/.*)
    #Druid数据源连接池配置
    datasource:
        druid:
            initialSize: 10
            minIdle: 10
            maxActive: 250
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            connectionInitSqls: set names utf8;
            filters: stat,slf4j

    mybatis:
        configLocation: classpath:config/mybatis/mybatis-config.xml
        mapperLocations: classpath:com/penglecode/xmodule/**/*Mapper.xml
        typeAliasesPackage: com.penglecode.xmodule
        mapperScanPackage: com.penglecode.xmodule