#应用日志配置
logging:
    path: /usr/local/xmodule/logs

spring:
    datasource:
        #默认数据源配置
        default: 
            username: root
            password: 123456
            url: jdbc:mysql://172.16.1.98:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false