#SpringBoot自动配置开启debug模式
debug: false

#应用日志配置
logging:
    file: ${spring.application.name}@${server.port}
    config: classpath:log4j2-spring.xml

#Spring上下文初始化程序
context:
    initializer:
        classes: com.penglecode.xmodule.common.initializer.DefaultSpringAppPreInitializer
        
#Servlet容器配置
server:
    port: 18181
    servlet:
        context-path: /
        application-display-name: ${spring.application.name}
        session:
            timeout: 1800
        #SpringMvc控制器路径配置
        path: /

#SpringBoot应用监控模块
management:
    server:
        port: ${server.port}
    endpoints:
        web:
            base-path: /admin/actuator
            exposure:
                include: '*'
    endpoint:
        shutdown:
            enabled: false
        health:
            show-details: always
    health:
        defaults:
            enabled: false

info:
    app:
        name: ${spring.application.name}
        description: SpringCloud服务生产者
        version: 1.0.0
        spring-cloud-version: Greenwich
        spring-boot-version: 2.1.2.RELEASE
        
#SpringBoot应用的名称
spring:
    #被排除的自动配置
    autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
          - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
    
    profiles:
        active: dev

    #Spring国际化配置
    messages:
        basename: config/i18/messages
        cache-duration: -1
        encoding: UTF-8
    #关闭JMX监控
    jmx:
        enabled: false
    #开启Web#CharacterEncodingFilter
    http:
        encoding:
            enabled: true
            charset: UTF-8
            force: true
    #SpringMvc上传文件配置
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 20MB
    #SpringMvc配置
    mvc:
        servlet:
            load-on-startup: 1

    security:
        filter:
            order: -2147483628
        user:
            name: admin
            password: 123456
            roles: ACTUATOR