#SpringBoot自动配置开启debug模式
debug: false

#应用日志配置
logging:
    config: classpath:log4j2-spring.xml

#Spring上下文初始化程序
context:
    initializer:
        classes: com.penglecode.xmodule.common.initializer.DefaultSpringAppPreInitializer
    listener:
        classes: com.penglecode.xmodule.common.listener.SpringEventListenerRegistryListener

#Servlet容器配置
server:
    port: 8080
    servlet:
        context-path: /
        application-display-name: xmodule-upms-server
        session:
            timeout: 1800

#SpringBoot应用监控模块
management:
    server:
        port: ${server.port}
    endpoints:
        web:
            base-path: /admin/actuator
            exposure:
                include: '*'
    endpoint:
        shutdown:
            enabled: false
        health:
            show-details: always
    health:
        defaults:
            enabled: false

info:
    app:
        name: "@project.name@"
        description: "@project.description@"
        version: "@project.version@"
        spring-boot-version: "@project.parent.parent.version@"
#SpringBoot应用的名称
spring:
    application:
        name: xmodule-upms-server
    #被排除的自动配置
    autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
          - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
          - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
        
    profiles:
        active: dev

    #Spring国际化配置
    messages:
        basename: config/i18/messages
        cache-duration: -1
        encoding: UTF-8
    #关闭JMX监控
    jmx:
        enabled: false
    #开启Web#CharacterEncodingFilter
    http:
        encoding:
            enabled: true
            charset: UTF-8
            force: true
    #SpringMvc上传文件配置
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 20MB
    #SpringMvc配置
    mvc:
        servlet:
            load-on-startup: 1
            #SpringMvc控制器路径配置
            path: /
    security:
        user:
            name: admin
            password: 123456
            roles: ACTUATOR
        config:
            login-url: /login.html
            default-login-success-url: /index.html
            unauthorized-url: /error/403.html
    #Druid数据源连接池配置
    datasource:
        druid:
            initialSize: 10
            minIdle: 10
            maxActive: 250
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            connectionInitSqls: set names utf8;
            filters: stat,slf4j
            

    mybatis:
        configLocation: classpath:config/mybatis/mybatis-config.xml
        mapperLocations: classpath:com/penglecode/xmodule/**/*Mapper.xml
        typeAliasesPackage: com.penglecode.xmodule
        mapperScanPackage: com.penglecode.xmodule
        
    #Redis共通配置
    redis:
        common:
            timeout: 6000
            lettuce:
                shutdownTimeout: 2000
                pool:
                    maxIdle: 8
                    minIdle: 0
                    maxActive: 8
                    maxWait: 30000
                
    cloud:
        #MVVM应用配置信息
        mvvmAppConfig:
            globalWebServerUrl: http://127.0.0.1
            globalFileServerUrl: http://127.0.0.1/static
            globalFileServerRoot: d:/nginxfiles/static
            appName: upms-server
            appDesc: 基于Spring-Security统一权限管理平台示例(多应用版)
            appWebServerUrl: http://127.0.0.1/upms-server
            appWebContextPath: /upms-server
            appApiServerUrl: http://127.0.0.1/upms-server-api
            appApiContextPath: /upms-server-api

upms:
    session:
        test: true