#应用日志配置
logging:
    path: d:/logs
    
spring:
    datasource:
        #默认数据源配置
        default: 
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/security_oauth2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false

    redis:
        #SpringSecurity使用的Redis配置
        security:
            host: 127.0.0.1
            port: 6379
            
    security:
        #OAuth2相关配置
        oauth2:
            client:
                token:
                    #storeType: memory
                    #checkUrl: http://127.0.0.1:8081/oauth/check_token
                    storeType: redis
                clientId: monkey
                clientSecret: d0763edaa9d9bd2a9516280e9044d885